In [49]:
## one hot encoding 정리 

import pandas as pd

data = {"eng":['b','c','a','d']}
df = pd.DataFrame(data)
print(type(df))
df

data2 = {"company":['MS','APPLE', 'NVIDIA', 'BLIZZARD']}
df2 = pd.DataFrame(data2)
df2



<class 'pandas.core.frame.DataFrame'>


company
0        MS
1     APPLE
2    NVIDIA
3  BLIZZARD

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [36]:
encoder_x = LabelEncoder()
df['lbl_encoder'] = encoder_x.fit_transform(df['eng'])
df_new = df.copy()
df_new = df_new.drop(['eng'],axis=1)
df_new

encoder_y = LabelEncoder()
df2['company_encoder'] = encoder_x.fit_transform(df2['company'])
df2_new = df2.copy()
df2_new = df2_new.drop(['company'],axis=1)
df2_new



company_encoder
0                2
1                0
2                3
3                1

In [37]:
df2

company  company_encoder
0        MS                2
1     APPLE                0
2    NVIDIA                3
3  BLIZZARD                1

In [38]:
val = df['lbl_encoder']
new_val = val.values
print(new_val.shape)
n = new_val.reshape(-1,1)
n.shape

val2 = df2['company_encoder']
new_val2 = val2.values 
n2 = new_val2.reshape(-1,1)
n2.shape

(4,)


(4, 1)

In [41]:
onehot = OneHotEncoder()
val = df['lbl_encoder']
new_val2 = val.values

n2 = new_val2.reshape(-1,1)
# .values.reshape(-1.1)

n2
y = onehot.fit_transform(n2).toarray()
print(y)

##############################3

onehot = OneHotEncoder()
val3 = df2['company_encoder']
new_val3 = val3.values

n3 = new_val3.reshape(-1,1)
y3 = onehot.fit_transform(n3).toarray()
print(y3)





[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you us

In [48]:
onehot_val = pd.DataFrame(y3,dtype=int)
onehot_val

all_df = pd.concat([df2, onehot_val], axis=1) 
print(all_df)



    company  company_encoder  0  1  2  3
0        MS                2  0  0  1  0
1     APPLE                0  1  0  0  0
2    NVIDIA                3  0  0  0  1
3  BLIZZARD                1  0  1  0  0
